import type { Guideline } from "./types";

/**
 * 医疗指南目录（AI 整理摘要版）
 * contentPath 对应 public/medical-guides/content/*.html
 */
export const guidelines: Guideline[] = [
  {
    id: "cma-hypertension-2018",
    title: "中国高血压防治指南（2018 修订版）",
    org: "中华医学会 / 中国高血压联盟",
    year: 2018,
    nodeIds: ["cma", "domestic", "icd10-ix", "icd11-11", "mesh-c14", "snomed-cv"],
    disease: "原发性高血压",
    codes: ["I10", "BA00"],
    summary: "中国成人高血压诊断、分层、生活方式与药物治疗的核心推荐。",
    tags: ["高血压", "心血管", "降压药"],
    sourceUrl: "https://www.chinahbp.org/",
    contentPath: "/medical-guides/content/cma-hypertension-2018.html",
  },
  {
    id: "aha-hypertension-2025",
    title: "AHA/ACC 高血压指南要点（整理版）",
    org: "AHA / ACC",
    year: 2025,
    nodeIds: ["aha", "international", "icd10-ix", "icd11-11", "mesh-c14", "snomed-cv"],
    disease: "高血压",
    codes: ["I10"],
    summary: "血压分类、心血管风险评估、一线药物与合并症管理要点。",
    tags: ["高血压", "AHA", "风险评估"],
    sourceUrl: "https://www.ahajournals.org/",
    contentPath: "/medical-guides/content/aha-hypertension-2025.html",
  },
  {
    id: "esc-hypertension-2024",
    title: "ESC 高血压管理指南要点",
    org: "ESC",
    year: 2024,
    nodeIds: ["esc", "international", "icd10-ix", "icd11-11", "mesh-c14", "snomed-cv"],
    disease: "高血压",
    codes: ["I10"],
    summary: "欧洲成人高血压诊断阈值、靶目标与联合治疗策略。",
    tags: ["高血压", "ESC", "联合治疗"],
    sourceUrl: "https://www.escardio.org/",
    contentPath: "/medical-guides/content/esc-hypertension-2024.html",
  },
  {
    id: "cma-diabetes-2024",
    title: "中国 2 型糖尿病防治指南（2020/更新要点）",
    org: "中华医学会糖尿病学分会",
    year: 2024,
    nodeIds: ["cma", "domestic", "icd10-iv", "icd11-05", "mesh-c18", "mesh-c19", "snomed-endo"],
    disease: "2 型糖尿病",
    codes: ["E11", "5A11"],
    summary: "筛查、血糖控制目标、口服药与胰岛素、并发症管理。",
    tags: ["糖尿病", "血糖", "代谢"],
    contentPath: "/medical-guides/content/cma-diabetes-2024.html",
  },
  {
    id: "ada-diabetes-2025",
    title: "ADA Standards of Care in Diabetes — 要点整理",
    org: "ADA",
    year: 2025,
    nodeIds: ["ada", "international", "icd10-iv", "icd11-05", "mesh-c18", "mesh-c19", "snomed-endo"],
    disease: "糖尿病",
    codes: ["E10", "E11"],
    summary: "诊断标准、个体化 A1C 目标、心肾获益药物与技术治疗。",
    tags: ["糖尿病", "ADA", "GLP-1", "SGLT2"],
    sourceUrl: "https://diabetesjournals.org/care",
    contentPath: "/medical-guides/content/ada-diabetes-2025.html",
  },
  {
    id: "who-diabetes-2023",
    title: "WHO 糖尿病诊断与管理建议（整理）",
    org: "WHO",
    year: 2023,
    nodeIds: ["who", "international", "icd10-iv", "icd11-05", "mesh-c19"],
    disease: "糖尿病",
    codes: ["E11"],
    summary: "全球层面的筛查、基础用药与初级卫生保健路径。",
    tags: ["糖尿病", "WHO", "初级保健"],
    sourceUrl: "https://www.who.int/",
    contentPath: "/medical-guides/content/who-diabetes-2023.html",
  },
  {
    id: "esc-hf-2021",
    title: "ESC 急慢性心力衰竭指南要点",
    org: "ESC",
    year: 2021,
    nodeIds: ["esc", "international", "icd10-ix", "icd11-11", "mesh-c14", "snomed-cv"],
    disease: "心力衰竭",
    codes: ["I50", "BD10"],
    summary: "HFrEF 四联基础治疗、表型分型与急性期处理。",
    tags: ["心衰", "HFrEF", "ARNI"],
    sourceUrl: "https://www.escardio.org/",
    contentPath: "/medical-guides/content/esc-hf-2021.html",
  },
  {
    id: "aha-hf-2022",
    title: "AHA/ACC/HFSA 心力衰竭指南要点",
    org: "AHA / ACC / HFSA",
    year: 2022,
    nodeIds: ["aha", "international", "icd10-ix", "icd11-11", "mesh-c14", "snomed-cv"],
    disease: "心力衰竭",
    codes: ["I50"],
    summary: "分期、GDMT、器械治疗与合并症管理框架。",
    tags: ["心衰", "GDMT", "分期"],
    contentPath: "/medical-guides/content/aha-hf-2022.html",
  },
  {
    id: "cma-acs-2019",
    title: "急性冠脉综合征急诊快速诊疗指南要点",
    org: "中华医学会急诊医学分会",
    year: 2019,
    nodeIds: ["cma", "domestic", "icd10-ix", "icd11-11", "mesh-c14", "snomed-cv"],
    disease: "急性冠脉综合征",
    codes: ["I21", "I20.0"],
    summary: "胸痛分诊、STEMI/NSTE-ACS 再灌注与抗栓策略。",
    tags: ["ACS", "STEMI", "抗栓"],
    contentPath: "/medical-guides/content/cma-acs-2019.html",
  },
  {
    id: "esc-acs-2023",
    title: "ESC 急性冠脉综合征指南要点",
    org: "ESC",
    year: 2023,
    nodeIds: ["esc", "international", "icd10-ix", "icd11-11", "mesh-c14"],
    disease: "急性冠脉综合征",
    codes: ["I21"],
    summary: "统一 ACS 路径、侵入策略时机与双抗疗程建议。",
    tags: ["ACS", "DAPT", "PCI"],
    contentPath: "/medical-guides/content/esc-acs-2023.html",
  },
  {
    id: "nccn-breast-2025",
    title: "NCCN 乳腺癌指南要点（整理版）",
    org: "NCCN",
    year: 2025,
    nodeIds: ["nccn", "international", "icd10-ii", "icd11-02", "mesh-c04", "snomed-onco"],
    disease: "乳腺癌",
    codes: ["C50"],
    summary: "分期、分子分型驱动的系统治疗与手术放疗原则。",
    tags: ["乳腺癌", "HER2", "激素受体"],
    sourceUrl: "https://www.nccn.org/",
    contentPath: "/medical-guides/content/nccn-breast-2025.html",
  },
  {
    id: "caca-breast-2024",
    title: "CACA 乳腺癌诊治指南要点",
    org: "CACA",
    year: 2024,
    nodeIds: ["caca", "domestic", "icd10-ii", "icd11-02", "mesh-c04", "snomed-onco"],
    disease: "乳腺癌",
    codes: ["C50"],
    summary: "中国人群乳腺癌筛查、诊疗路径与随访建议。",
    tags: ["乳腺癌", "CACA", "筛查"],
    contentPath: "/medical-guides/content/caca-breast-2024.html",
  },
  {
    id: "nccn-nsclc-2025",
    title: "NCCN 非小细胞肺癌指南要点",
    org: "NCCN",
    year: 2025,
    nodeIds: ["nccn", "international", "icd10-ii", "icd11-02", "mesh-c04", "snomed-onco"],
    disease: "非小细胞肺癌",
    codes: ["C34"],
    summary: "驱动基因检测、靶向/免疫与局部晚期综合治疗。",
    tags: ["肺癌", "EGFR", "PD-1"],
    contentPath: "/medical-guides/content/nccn-nsclc-2025.html",
  },
  {
    id: "caca-lung-2024",
    title: "CACA 肺癌诊治指南要点",
    org: "CACA",
    year: 2024,
    nodeIds: ["caca", "domestic", "icd10-ii", "icd11-02", "mesh-c04"],
    disease: "肺癌",
    codes: ["C34"],
    summary: "低剂量 CT 筛查、病理分子检测与分期治疗框架。",
    tags: ["肺癌", "LDCT", "分子分型"],
    contentPath: "/medical-guides/content/caca-lung-2024.html",
  },
  {
    id: "nccn-crc-2025",
    title: "NCCN 结直肠癌指南要点",
    org: "NCCN",
    year: 2025,
    nodeIds: ["nccn", "international", "icd10-ii", "icd11-02", "mesh-c04", "snomed-onco"],
    disease: "结直肠癌",
    codes: ["C18", "C20"],
    summary: "筛查、新辅助/辅助化疗、转移性治疗与 MSI 检测。",
    tags: ["结直肠癌", "MSI", "筛查"],
    contentPath: "/medical-guides/content/nccn-crc-2025.html",
  },
  {
    id: "nice-depression-2022",
    title: "NICE 抑郁识别与管理指南要点",
    org: "NICE",
    year: 2022,
    nodeIds: ["nice", "international", "icd10-v", "icd11-06", "mesh-f03"],
    disease: "抑郁障碍",
    codes: ["F32", "6A70"],
    summary: "阶梯治疗、心理与药物干预、复发预防。",
    tags: ["抑郁", "心理治疗", "抗抑郁药"],
    sourceUrl: "https://www.nice.org.uk/",
    contentPath: "/medical-guides/content/nice-depression-2022.html",
  },
  {
    id: "cma-depression-2015",
    title: "中国抑郁障碍防治指南要点",
    org: "中华医学会精神医学分会",
    year: 2015,
    nodeIds: ["cma", "domestic", "icd10-v", "icd11-06", "mesh-f03"],
    disease: "抑郁障碍",
    codes: ["F32"],
    summary: "诊断评估、急性期与维持期用药、物理治疗指征。",
    tags: ["抑郁", "精神科"],
    contentPath: "/medical-guides/content/cma-depression-2015.html",
  },
  {
    id: "gold-copd-2025",
    title: "GOLD 慢性阻塞性肺疾病指南要点",
    org: "GOLD / ATS 相关",
    year: 2025,
    nodeIds: ["ats", "international", "icd10-x", "icd11-12", "mesh-c08", "snomed-resp"],
    disease: "慢性阻塞性肺疾病",
    codes: ["J44"],
    summary: "ABCD/ABE 分组、支气管扩张剂、急性加重与共病。",
    tags: ["COPD", "GOLD", "吸入治疗"],
    contentPath: "/medical-guides/content/gold-copd-2025.html",
  },
  {
    id: "gina-asthma-2024",
    title: "GINA 哮喘管理与预防策略要点",
    org: "GINA / ATS·ERS 相关",
    year: 2024,
    nodeIds: ["ats", "international", "icd10-x", "icd11-12", "mesh-c08", "snomed-resp"],
    disease: "支气管哮喘",
    codes: ["J45"],
    summary: "ICS 为基础的阶梯治疗、症状驱动方案与生物制剂。",
    tags: ["哮喘", "GINA", "ICS"],
    contentPath: "/medical-guides/content/gina-asthma-2024.html",
  },
  {
    id: "cma-copd-2021",
    title: "慢性阻塞性肺疾病诊治指南（中国）要点",
    org: "中华医学会呼吸病学分会",
    year: 2021,
    nodeIds: ["cma", "domestic", "icd10-x", "icd11-12", "mesh-c08"],
    disease: "慢性阻塞性肺疾病",
    codes: ["J44"],
    summary: "中国人群诊断、稳定期与急性加重期治疗路径。",
    tags: ["COPD", "呼吸"],
    contentPath: "/medical-guides/content/cma-copd-2021.html",
  },
  {
    id: "kdigo-ckd-2024",
    title: "KDIGO CKD 评估与管理指南要点",
    org: "KDIGO",
    year: 2024,
    nodeIds: ["kdigo", "international", "icd10-xiv", "icd11-16", "mesh-c12"],
    disease: "慢性肾脏病",
    codes: ["N18"],
    summary: "GFR/白蛋白尿分期、血压血糖血脂与 SGLT2 等肾保护。",
    tags: ["CKD", "KDIGO", "肾病"],
    sourceUrl: "https://kdigo.org/",
    contentPath: "/medical-guides/content/kdigo-ckd-2024.html",
  },
  {
    id: "nhc-ckd-2022",
    title: "慢性肾脏病筛查与防治相关规范要点",
    org: "国家卫健委 / 相关专委会",
    year: 2022,
    nodeIds: ["nhc", "domestic", "icd10-xiv", "icd11-16", "mesh-c12"],
    disease: "慢性肾脏病",
    codes: ["N18"],
    summary: "基层筛查、转诊指征与一体化管理建议。",
    tags: ["CKD", "基层", "筛查"],
    contentPath: "/medical-guides/content/nhc-ckd-2022.html",
  },
  {
    id: "aha-stroke-2021",
    title: "AHA/ASA 急性缺血性卒中早期管理要点",
    org: "AHA / ASA",
    year: 2021,
    nodeIds: ["aha", "international", "icd10-ix", "icd11-08", "mesh-c10", "snomed-neuro"],
    disease: "急性缺血性卒中",
    codes: ["I63"],
    summary: "溶栓时间窗、取栓适应证与卒中单元路径。",
    tags: ["卒中", "溶栓", "取栓"],
    contentPath: "/medical-guides/content/aha-stroke-2021.html",
  },
  {
    id: "cma-stroke-2023",
    title: "中国急性缺血性卒中诊治指南要点",
    org: "中华医学会神经病学分会",
    year: 2023,
    nodeIds: ["cma", "domestic", "icd10-ix", "icd11-08", "mesh-c10", "snomed-neuro"],
    disease: "急性缺血性卒中",
    codes: ["I63"],
    summary: "再灌注治疗、抗栓与二级预防中国实践要点。",
    tags: ["卒中", "二级预防"],
    contentPath: "/medical-guides/content/cma-stroke-2023.html",
  },
  {
    id: "who-hypertension-2021",
    title: "WHO 成人高血压药物治疗指南要点",
    org: "WHO",
    year: 2021,
    nodeIds: ["who", "international", "icd10-ix", "icd11-11", "mesh-c14"],
    disease: "高血压",
    codes: ["I10"],
    summary: "面向初级保健的起始联合治疗与简化方案。",
    tags: ["高血压", "WHO", "初级保健"],
    contentPath: "/medical-guides/content/who-hypertension-2021.html",
  },
  {
    id: "nice-hypertension-2023",
    title: "NICE 高血压诊断与管理要点",
    org: "NICE",
    year: 2023,
    nodeIds: ["nice", "international", "icd10-ix", "mesh-c14"],
    disease: "高血压",
    codes: ["I10"],
    summary: "诊室/动态血压诊断、阶梯用药与监测随访。",
    tags: ["高血压", "NICE", "ABPM"],
    contentPath: "/medical-guides/content/nice-hypertension-2023.html",
  },
  {
    id: "uspstf-lung-2021",
    title: "USPSTF 肺癌筛查推荐要点",
    org: "USPSTF",
    year: 2021,
    nodeIds: ["uspstf", "international", "icd10-ii", "mesh-c04"],
    disease: "肺癌（筛查）",
    codes: ["Z12.2"],
    summary: "高危吸烟人群低剂量 CT 筛查年龄与包年标准。",
    tags: ["筛查", "LDCT", "预防"],
    contentPath: "/medical-guides/content/uspstf-lung-2021.html",
  },
  {
    id: "uspstf-crc-2021",
    title: "USPSTF 结直肠癌筛查推荐要点",
    org: "USPSTF",
    year: 2021,
    nodeIds: ["uspstf", "international", "icd10-ii", "mesh-c04"],
    disease: "结直肠癌（筛查）",
    codes: ["Z12.1"],
    summary: "45–75 岁筛查起止年龄与多种筛查方式选择。",
    tags: ["筛查", "肠镜", "FIT"],
    contentPath: "/medical-guides/content/uspstf-crc-2021.html",
  },
  {
    id: "acog-gdm-2018",
    title: "ACOG 妊娠期糖尿病指南要点",
    org: "ACOG",
    year: 2018,
    nodeIds: ["acog", "international", "icd10-xv", "icd10-iv", "mesh-c19"],
    disease: "妊娠期糖尿病",
    codes: ["O24.4"],
    summary: "筛查时机、血糖目标、饮食运动与胰岛素指征。",
    tags: ["妊娠", "GDM", "产科"],
    contentPath: "/medical-guides/content/acog-gdm-2018.html",
  },
  {
    id: "nhc-maternal-2022",
    title: "孕产妇健康管理相关规范要点",
    org: "国家卫健委",
    year: 2022,
    nodeIds: ["nhc", "domestic", "icd10-xv"],
    disease: "孕产期保健",
    codes: ["Z34"],
    summary: "产前检查频次、高危妊娠识别与转诊路径。",
    tags: ["孕产", "保健", "基层"],
    contentPath: "/medical-guides/content/nhc-maternal-2022.html",
  },
  {
    id: "cmda-pain-2020",
    title: "癌症疼痛诊疗规范要点",
    org: "中国医师协会 / 相关专委会",
    year: 2020,
    nodeIds: ["cmda", "domestic", "icd10-ii", "mesh-c04"],
    disease: "癌痛",
    codes: ["R52"],
    summary: "三阶梯镇痛、滴定、爆发痛与阿片不良反应管理。",
    tags: ["癌痛", "镇痛", "姑息"],
    contentPath: "/medical-guides/content/cmda-pain-2020.html",
  },
  {
    id: "cma-hbv-2022",
    title: "慢性乙型肝炎防治指南要点",
    org: "中华医学会肝病学分会",
    year: 2022,
    nodeIds: ["cma", "domestic", "icd10-i", "icd11-01", "icd10-xi", "icd11-13"],
    disease: "慢性乙型肝炎",
    codes: ["B18.1"],
    summary: "抗病毒适应证、核苷（酸）类似物与干扰素策略。",
    tags: ["乙肝", "抗病毒", "肝病"],
    contentPath: "/medical-guides/content/cma-hbv-2022.html",
  },
  {
    id: "who-hbv-2024",
    title: "WHO 慢性乙肝预防、诊断与治疗指南要点",
    org: "WHO",
    year: 2024,
    nodeIds: ["who", "international", "icd10-i", "icd11-01", "icd10-xi"],
    disease: "慢性乙型肝炎",
    codes: ["B18.1"],
    summary: "扩大治疗适应证、简化监测与母婴阻断。",
    tags: ["乙肝", "WHO", "母婴阻断"],
    contentPath: "/medical-guides/content/who-hbv-2024.html",
  },
  {
    id: "nice-ckd-2021",
    title: "NICE 慢性肾脏病评估与管理要点",
    org: "NICE",
    year: 2021,
    nodeIds: ["nice", "international", "icd10-xiv", "mesh-c12"],
    disease: "慢性肾脏病",
    codes: ["N18"],
    summary: "诊断分类、心血管风险、转诊与药物注意。",
    tags: ["CKD", "NICE"],
    contentPath: "/medical-guides/content/nice-ckd-2021.html",
  },
  {
    id: "esc-af-2024",
    title: "ESC 心房颤动管理指南要点",
    org: "ESC",
    year: 2024,
    nodeIds: ["esc", "international", "icd10-ix", "icd11-11", "mesh-c14", "snomed-cv"],
    disease: "心房颤动",
    codes: ["I48"],
    summary: "AF-CARE 路径、抗凝、节律/室率控制与共病。",
    tags: ["房颤", "抗凝", "ABC"],
    contentPath: "/medical-guides/content/esc-af-2024.html",
  },
  {
    id: "cma-af-2023",
    title: "心房颤动诊断和治疗中国指南要点",
    org: "中华医学会心电生理和起搏分会等",
    year: 2023,
    nodeIds: ["cma", "domestic", "icd10-ix", "mesh-c14", "snomed-cv"],
    disease: "心房颤动",
    codes: ["I48"],
    summary: "中国人群抗凝、消融适应证与整合管理。",
    tags: ["房颤", "消融", "抗凝"],
    contentPath: "/medical-guides/content/cma-af-2023.html",
  },
  {
    id: "ada-ckd-2025",
    title: "ADA 糖尿病肾病管理要点（Standards 摘录）",
    org: "ADA",
    year: 2025,
    nodeIds: ["ada", "international", "icd10-iv", "icd10-xiv", "mesh-c18", "mesh-c12"],
    disease: "糖尿病肾脏病",
    codes: ["E11.2", "N18"],
    summary: "筛查频率、SGLT2/nsMRA 与血压血脂协同管理。",
    tags: ["糖尿病肾病", "SGLT2", "蛋白尿"],
    contentPath: "/medical-guides/content/ada-ckd-2025.html",
  },
  {
    id: "nhc-infection-control-2023",
    title: "医疗机构感染预防与控制相关规范要点",
    org: "国家卫健委",
    year: 2023,
    nodeIds: ["nhc", "domestic", "icd10-i"],
    disease: "医院感染防控",
    codes: [],
    summary: "手卫生、隔离、抗菌药物管理与暴发处置框架。",
    tags: ["感控", "HAI", "抗菌药物"],
    contentPath: "/medical-guides/content/nhc-infection-control-2023.html",
  },
  {
    id: "who-amr-2023",
    title: "WHO 抗菌药物耐药（AMR）应对要点",
    org: "WHO",
    year: 2023,
    nodeIds: ["who", "international", "icd10-i"],
    disease: "抗菌药物耐药",
    codes: [],
    summary: "AWaRe 分类、监测与合理使用核心干预。",
    tags: ["AMR", "AWaRe", "抗生素"],
    contentPath: "/medical-guides/content/who-amr-2023.html",
  },
  {
    id: "caca-gastric-2024",
    title: "CACA 胃癌诊治指南要点",
    org: "CACA",
    year: 2024,
    nodeIds: ["caca", "domestic", "icd10-ii", "icd11-02", "mesh-c04", "icd10-xi"],
    disease: "胃癌",
    codes: ["C16"],
    summary: "早诊早治、围手术期治疗与晚期系统治疗路径。",
    tags: ["胃癌", "CACA", "幽门螺杆菌"],
    contentPath: "/medical-guides/content/caca-gastric-2024.html",
  },
];

export function getGuidelineById(id: string): Guideline | undefined {
  return guidelines.find((g) => g.id === id);
}

export function searchGuidelines(query: string, nodeId?: string | null): Guideline[] {
  const q = query.trim().toLowerCase();
  return guidelines.filter((g) => {
    const nodeOk = !nodeId || nodeId === "root" || g.nodeIds.includes(nodeId);
    if (!nodeOk) return false;
    if (!q) return true;
    const hay = [
      g.title,
      g.org,
      g.disease,
      g.summary,
      ...g.tags,
      ...(g.codes || []),
      String(g.year),
    ]
      .join(" ")
      .toLowerCase();
    return hay.includes(q);
  });
}
